name: aqar_app
description: "A comprehensive real estate mobile application built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.1.6
  jwt_decoder: ^2.0.1
  socket_io_client: ^3.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_local_notifications: ^16.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0  # إضافة حزمة Google Fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

dependency_overrides:
  web: ^0.5.1